TP1 advanced database



SELECT * FROM EMP;
SELECT ENAME FROM EMP WHERE COMM>SAL;
SELECT ENAME FROM EMP WHERE SAL>1200 AND SAL<1400;
SELECT ENAME FROM EMP WHERE JOB='ANALYST' OR JOB='CLERK';
SELECT ENAME FROM EMP WHERE ENAME LIKE 'M%';
SELECT ENAME FROM EMP WHERE ENAME LIKE '_L%';
SELECT ENAME FROM EMP WHERE (JOB='CLERK' OR JOB='MANAGER') AND (DEPTNO=10) AND (SAL>1500);
SELECT ENAME FROM EMP WHERE COMM IS NULL;
SELECT ENAME FROM EMP ORDER BY ENAME ASC;
SELECT ENAME,JOB,SAL FROM EMP ORDER by JOB,SAL ASC;
SELECT D.DNAME FROM DEPT D, EMP E WHERE E.DEPTNO!=D.DEPTNO;
SELECT E.ENAME,E2.ENAME,E.DEPTNO FROM EMP E, EMP E2 WHERE E.DEPTNO=E2.DEPTNO AND E.JOB!='MANAGER' AND E2.JOB='MANAGER' ORDER BY E.DEPTNO ASC;
SELECT E.ENAME FROM EMP E, EMP E2 WHERE E2.ENAME='JONES' AND E.SAL>E2.SAL;
SELECT E.ENAME FROM EMP E, EMP E2 WHERE E2.SAL=E2.SAL AND E.COMM=E2.COMM;
SELECT DEPTNO FROM DEPT INTERSECT SELECT DEPTNO FROM EMP;
SELECT E.ENAME FROM EMP E,EMP E2, DEPT D WHERE D.DEPTNO=E.DEPTNO AND D.LOC='CHICAGO' AND E2.NAME='JONES' AND E.JOB=E2.JOB;
SELECT E.ENAME,E2.ENAME,E.DEPTNO FROM EMP E, EMP E2 WHERE E.DEPTNO!=E2.DEPTNO AND E.JOB!='MANAGER' AND E2.JOB='MANAGER' ORDER BY E.DEPTNO ASC;
















SELECT E.ENAME FROM EMP E, EMP E2 WHERE (E2.NAME='JONES' AND E.JOB=E2.JOB) UNION SELECT E.ENAME FROM EMP E, EMP E2 WHERE (E2.NAME='FORD' AND E.SAL>E2.SAL);
